### ISSUE TITLE
Simpler use case

### ISSUE THREAD

**Issue by keesterbrugge** [techascent/tvm-clj#13]
Hi Chris,

I'm quite excited about what tvm has to offer, so thank you for contributing these bindings! 

You've provided a nice box-blur example that shows the amount of control that tvm-clj offers. I'm trying to determine whether tvm-clj can also be used in a less advanced way to speed up numerical code, in a way similar to pydata's [numba](http://numba.pydata.org/) and [geex](https://github.com/jonasseglare/geex). Perhaps with the use of [AutoTVM](https://arxiv.org/pdf/1805.08166.pdf) to find a schedule automatically. 

Would something like that be possible?

Cheers

**Comment by cnuernber** [comment]
We are having a discussion on the zulip tvm page about this at this very moment.  Generating jvm bytecode for some subset of the tvm system sounds hard, but reasonable.  Currently it appears that geex generates great bytecode so on the jvm so some pathway from geex to a subset of of the tvm language that generates code for the jvm seems reasonable.

I think for mainly scalar type operations geex is where you want to be.  As you move to n-dimensional operations then some subset of the tvm/halide language on the jvm is the best point.  

Then you have tvm to go to pure assembly or gpu or whatever else. 

[Here](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/tvm/near/161187447) is the zulip discussion.

**Comment by keesterbrugge** [comment]
Thanks for the explanation. I'll follow the discussion over there.
